eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://ratingsuser:admin123@mongodb-svc:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: ratings-db
      port: 27017




  application:
    name: RATING-SERVICE
  
#  config:
#    import: configserver:http://localhost:8888/
